import type { PromptVersion } from "../../domain/prompt/index.js";
import type { EntityId, ProjectId } from "../../domain/shared/id.js";

export const GENERATION_CAPABILITIES = ["generate", "variation", "edit", "cancel", "retry"] as const;
export type GenerationCapability = (typeof GENERATION_CAPABILITIES)[number];
export interface GenerationProviderMetadata { readonly id: string; readonly label: string; readonly mock: boolean; readonly capabilities: readonly GenerationCapability[]; }
export interface GenerationRequest { readonly projectId: ProjectId; readonly promptVersion: PromptVersion; readonly operation: "generate" | "variation" | "edit"; readonly sourceAssetId?: EntityId; readonly instruction?: string; readonly seed: string; readonly signal?: AbortSignal; }
export type GenerationEvent = { readonly type: "queued" } | { readonly type: "progress"; readonly progress: number; readonly message: string } | { readonly type: "result"; readonly result: GenerationResult } | { readonly type: "error"; readonly code: string; readonly message: string } | { readonly type: "cancelled" };
export interface GenerationResult { readonly fixtureKey: string; readonly mimeType: "image/webp" | "image/png" | "image/jpeg"; readonly width: number; readonly height: number; readonly seed: string; readonly byteSize: number; readonly assetUrl?: string; readonly providerId?: string; readonly model?: string; readonly modelVersion?: string; readonly providerRunId?: string; readonly estimatedCostCny?: number; }
export interface GenerationProvider { readonly metadata: GenerationProviderMetadata; generate(request: GenerationRequest): AsyncIterable<GenerationEvent>; variation(request: GenerationRequest): AsyncIterable<GenerationEvent>; edit(request: GenerationRequest): AsyncIterable<GenerationEvent>; cancel(jobId: EntityId): Promise<void>; retry(request: GenerationRequest): AsyncIterable<GenerationEvent>; }
export class GenerationProviderError extends Error { constructor(readonly code: "UNSUPPORTED_CAPABILITY" | "INVALID_EVENT" | "PROVIDER_FAILURE" | "CANCELLED", message: string) { super(message); this.name = "GenerationProviderError"; } }
export function requireGenerationCapability(metadata: GenerationProviderMetadata, capability: GenerationCapability): void { if (!metadata.capabilities.includes(capability)) throw new GenerationProviderError("UNSUPPORTED_CAPABILITY", `${metadata.label} does not support ${capability}.`); }
export function validateGenerationEvent(event: GenerationEvent): GenerationEvent { if (event.type === "progress" && (event.progress < 0 || event.progress > 100 || !event.message.trim())) throw new GenerationProviderError("INVALID_EVENT", "Generation progress must be 0–100 with a message."); if (event.type === "result" && (!event.result.fixtureKey.trim() || event.result.width <= 0 || event.result.height <= 0 || event.result.byteSize <= 0)) throw new GenerationProviderError("INVALID_EVENT", "Generation result metadata is invalid."); if (event.type === "error" && (!event.code.trim() || !event.message.trim())) throw new GenerationProviderError("INVALID_EVENT", "Generation error is incomplete."); return event; }
