export { isProject, isProjectBrief } from "./guards.js";
export {
  PROJECT_OUTPUT_TYPES,
  PROJECT_STAGES,
  PROJECT_STATUSES,
  PROJECT_TYPES,
  DESIGN_DOMAINS,
  INFORMATION_ORIGINS,
  OUTCOME_CATEGORIES,
} from "./types.js";
export type {
  Assumption,
  BriefItem,
  Criterion,
  DesignBrief,
  DesignDomain,
  DesignDomainContext,
  ExpectedOutcome,
  InformationOrigin,
  OriginalBriefSnapshot,
  Project,
  ProjectBrief,
  ProjectExpectedOutcomes,
  ProjectOutputType,
  ProjectOverview,
  ProjectOverviewConflict,
  ProjectOverviewTargetUser,
  ProjectUnderstandingVersion,
  ProjectSettings,
  ProjectStage,
  ProjectStatus,
  ProjectType,
  ResearchQuestion,
  SuggestedOutcome,
  Unknown,
} from "./types.js";
