import assert from "node:assert/strict";
import test from "node:test";
import { CanvasNodeCommandService, EntityCanvasAdapter } from "../../src/application/canvas/index.js";
import { CanvasRepository } from "../../src/repositories/CanvasRepository.js";
import { gateDatabase } from "../helpers/phase-one-case.js";
import { createPromptCase } from "../helpers/prompt-case.js";

void test("deleting a canvas node removes related edges but preserves the domain entity", async () => { const database = gateDatabase("p17-node-delete"); try { const fixture = await createPromptCase(database, 82, "山西文化遗产"); const repository = new CanvasRepository(database); const canvas = await repository.createCanvas({ id: fixture.nextId(), projectId: fixture.projectId, name: "Map" }); const adapter = new EntityCanvasAdapter(database, { entityIdFactory: fixture.nextId }); const briefNode = await adapter.add(fixture.projectId, canvas.id, "brief", fixture.briefId, { x: 0, y: 0 }); const researchNode = await adapter.add(fixture.projectId, canvas.id, "research", fixture.researchSessionId, { x: 200, y: 0 }); const edge = await repository.createEdge({ id: fixture.nextId(), projectId: fixture.projectId, canvasId: canvas.id, sourceNodeId: briefNode.id, targetNodeId: researchNode.id, label: "lineage" }); const result = await new CanvasNodeCommandService(database).deleteViewNode(fixture.projectId, briefNode.id); assert.equal(result.businessEntityDeleted, false); assert.equal(await repository.getEdge(edge.id), undefined); assert.ok(await database.table("briefs").get(fixture.briefId)); } finally { database.close(); } });

void test("explicit domain deletion leaves a stale node that can be pruned without cascading", async () => { const database = gateDatabase("p17-node-prune"); try { const fixture = await createPromptCase(database, 83, "成都独立咖啡"); const repository = new CanvasRepository(database); const canvas = await repository.createCanvas({ id: fixture.nextId(), projectId: fixture.projectId, name: "Map" }); const node = await new EntityCanvasAdapter(database, { entityIdFactory: fixture.nextId }).add(fixture.projectId, canvas.id, "brief", fixture.briefId, { x: 0, y: 0 }); await database.table("briefs").delete(fixture.briefId); assert.ok(await repository.getNode(node.id)); assert.deepEqual(await new CanvasNodeCommandService(database).pruneMissingEntityNodes(fixture.projectId, canvas.id), [node.id]); assert.equal(await repository.getNode(node.id), undefined); } finally { database.close(); } });

void test("node deletion rolls back edges and node on failure", async () => { const database = gateDatabase("p17-node-rollback"); try { const fixture = await createPromptCase(database, 84, "山西文化遗产"); const repository = new CanvasRepository(database); const canvas = await repository.createCanvas({ id: fixture.nextId(), projectId: fixture.projectId, name: "Map" }); const adapter = new EntityCanvasAdapter(database, { entityIdFactory: fixture.nextId }); const source = await adapter.add(fixture.projectId, canvas.id, "brief", fixture.briefId, { x: 0, y: 0 }); const target = await adapter.add(fixture.projectId, canvas.id, "research", fixture.researchSessionId, { x: 1, y: 1 }); const edge = await repository.createEdge({ id: fixture.nextId(), projectId: fixture.projectId, canvasId: canvas.id, sourceNodeId: source.id, targetNodeId: target.id }); await assert.rejects(() => new CanvasNodeCommandService(database, { faultInjector: () => { throw new Error("fault"); } }).deleteViewNode(fixture.projectId, source.id)); assert.ok(await repository.getNode(source.id)); assert.ok(await repository.getEdge(edge.id)); } finally { database.close(); } });
