import assert from "node:assert/strict";
import test from "node:test";
import { EntityCanvasAdapter, LineageEdgeService } from "../../src/application/canvas/index.js";
import { ReviewService } from "../../src/application/review/index.js";
import type { ProjectScopedEntity } from "../../src/domain/shared/entity.js";
import type { EntityId } from "../../src/domain/shared/id.js";
import { CanvasRepository } from "../../src/repositories/CanvasRepository.js";
import { gateDatabase } from "../helpers/phase-one-case.js";
import { createGeneratedCase } from "../helpers/generation-case.js";

void test("lineage edges rebuild deterministically across the full chain and branch directions", async () => { const database = gateDatabase("p17-lineage"); try { const fixture = await createGeneratedCase(database, 77, "山西文化遗产"); const reviewed = await new ReviewService(database, { entityIdFactory: fixture.nextId }).review(fixture.projectId, fixture.generatedAssetId); const repository = new CanvasRepository(database); const canvas = await repository.createCanvas({ id: fixture.nextId(), projectId: fixture.projectId, name: "决策地图" }); const first = async (table: string) => { const entity = await database.table<ProjectScopedEntity, EntityId>(table).where("projectId").equals(fixture.projectId).first(); if (!entity) throw new Error(`Missing ${table}`); return entity.id; }; const adapter = new EntityCanvasAdapter(database, { entityIdFactory: fixture.nextId }); const refs = [["brief", fixture.briefId], ["research", fixture.researchSessionId], ["insight", await first("researchInsights")], ["opportunity", await first("researchOpportunities")], ["moodboard", fixture.moodboardId], ...fixture.directionIds.map(id => ["direction", id] as const), ["exploration", fixture.explorationId], ["prompt", fixture.promptVersionId], ["generated_asset", fixture.generatedAssetId], ["asset", fixture.assetId], ["review", reviewed.review.id]] as const; for (const [index, ref] of refs.entries()) await adapter.add(fixture.projectId, canvas.id, ref[0], ref[1], { x: index * 100, y: 0 }); const service = new LineageEdgeService(database); const firstRun = await service.rebuild(fixture.projectId, canvas.id); const secondRun = await service.rebuild(fixture.projectId, canvas.id); assert.ok(firstRun.length >= 10); assert.deepEqual(secondRun.map(edge => edge.id).sort(), firstRun.map(edge => edge.id).sort()); assert.equal(new Set(secondRun.map(edge => edge.id)).size, secondRun.length); } finally { database.close(); } });

void test("lineage rebuild removes stale managed edges and rejects missing node entities", async () => { const database = gateDatabase("p17-lineage-stale"); try { const fixture = await createGeneratedCase(database, 78, "成都独立咖啡"); const repository = new CanvasRepository(database); const canvas = await repository.createCanvas({ id: fixture.nextId(), projectId: fixture.projectId, name: "决策地图" }); const adapter = new EntityCanvasAdapter(database, { entityIdFactory: fixture.nextId }); const source = await adapter.add(fixture.projectId, canvas.id, "brief", fixture.briefId, { x: 0, y: 0 }); const target = await adapter.add(fixture.projectId, canvas.id, "research", fixture.researchSessionId, { x: 200, y: 0 }); const stale = await repository.createEdge({ id: fixture.nextId(), projectId: fixture.projectId, canvasId: canvas.id, sourceNodeId: target.id, targetNodeId: source.id, label: "lineage" }); const edges = await new LineageEdgeService(database).rebuild(fixture.projectId, canvas.id); assert.ok(!edges.some(edge => edge.id === stale.id)); await database.table("researchSessions").delete(fixture.researchSessionId); await assert.rejects(() => new LineageEdgeService(database).rebuild(fixture.projectId, canvas.id)); } finally { database.close(); } });
