import type { Direction, DirectionReference } from "../../domain/direction/index.js";
import type { VisualDNA } from "../../domain/moodboard/index.js";
import type { EntityId } from "../../domain/shared/id.js";
import type { VariationAxis, VariationAxisValue } from "./variation.js";
import { validateVariationAxisValues, variationDifferenceCount } from "./variation.js";
export interface IterationIntent { readonly text: string; readonly focusAxes: readonly VariationAxis[]; }
export interface ExplorationProviderInput { readonly direction: Direction & { readonly status: "locked" }; readonly visualDNA: VisualDNA; readonly references: readonly DirectionReference[]; readonly sourceAssetIds: readonly EntityId[]; readonly axes: readonly VariationAxis[]; readonly seed: string; readonly iterationIntent?: IterationIntent; readonly signal?: AbortSignal; }
export interface ExplorationVariantCandidate { readonly key: string; readonly conceptId: EntityId; readonly label: string; readonly axisValues: readonly VariationAxisValue[]; readonly referenceIds: readonly EntityId[]; readonly sourceAssetIds: readonly EntityId[]; readonly preview: { readonly fixtureKey: string; readonly width: number; readonly height: number; readonly mimeType: "image/webp" }; }
export interface ExplorationProviderOutput { readonly variants: readonly ExplorationVariantCandidate[]; }
export interface ExplorationProvider { generate(input: ExplorationProviderInput): Promise<ExplorationProviderOutput>; }
export class ExplorationProviderError extends Error { constructor(readonly code: "CANCELLED" | "INVALID_OUTPUT" | "PROVIDER_FAILURE", message: string) { super(message); this.name = "ExplorationProviderError"; } }
export function validateExplorationProviderOutput(output: ExplorationProviderOutput, input: ExplorationProviderInput): ExplorationProviderOutput { const variants = output.variants; const allowedReferences = new Set(input.references.map((item) => item.id)); const allowedAssets = new Set(input.sourceAssetIds); const valid = variants.length >= 4 && variants.length <= 6 && new Set(variants.map((item) => item.key)).size === variants.length && new Set(variants.map((item) => item.preview.fixtureKey)).size === variants.length && variants.every((item) => item.conceptId === input.direction.id && item.label.trim() && item.preview.width > 0 && item.preview.height > 0 && item.referenceIds.every((id) => allowedReferences.has(id)) && item.sourceAssetIds.length > 0 && item.sourceAssetIds.every((id) => allowedAssets.has(id)) && validateVariationAxisValues(item.axisValues).length > 0); if (!valid) throw new ExplorationProviderError("INVALID_OUTPUT", "Exploration provider output violates count, concept, provenance or fixture rules."); for (let left = 0; left < variants.length; left += 1) for (let right = left + 1; right < variants.length; right += 1) if (variationDifferenceCount(variants[left]?.axisValues ?? [], variants[right]?.axisValues ?? []) < 2) throw new ExplorationProviderError("INVALID_OUTPUT", "Exploration variants must differ on multiple visual axes."); return output; }
