import { ensureDecisionMap, EntityCanvasAdapter, LineageEdgeService } from "../../src/application/canvas/index.js";
import { DirectionCommandService } from "../../src/application/direction/index.js";
import { ExplorationService } from "../../src/application/exploration/index.js";
import { GeneratedAssetService, GenerationJobService } from "../../src/application/generation/index.js";
import { PromptAdapterService, PromptCompiler } from "../../src/application/prompt/index.js";
import { ReviewService } from "../../src/application/review/index.js";
import type { Direction } from "../../src/domain/direction/index.js";
import type { Exploration, ExplorationVariant } from "../../src/domain/exploration/index.js";
import type { Moodboard, VisualDNA } from "../../src/domain/moodboard/index.js";
import type { Project, ProjectBrief } from "../../src/domain/project/index.js";
import type { ResearchInsight, ResearchSession } from "../../src/domain/research/index.js";
import type { EntityId } from "../../src/domain/shared/id.js";
import type { MuseDatabase } from "../../src/db/database.js";
import { deterministicPromptAdapters } from "../../src/infrastructure/providers/mock/prompt-adapters/index.js";
import { createLockedDirectionCase } from "./phase-one-case.js";

async function required<T>(database: MuseDatabase, table: string, id: EntityId): Promise<T> { const value = await database.table<T, EntityId>(table).get(id); if (!value) throw new Error(`Missing ${table}:${id}`); return value; }
export async function runFinalPhaseOneCase(database: MuseDatabase, caseNumber: number, name: string) {
  const base = await createLockedDirectionCase(database, caseNumber, name); const lockedDirectionId = base.directionIds[1]; if (!lockedDirectionId) throw new Error("Direction B missing"); await new DirectionCommandService(database).lock(base.projectId, lockedDirectionId);
  const explorationResult = await new ExplorationService(database, { entityIdFactory: base.nextId }).generate({ projectId: base.projectId, visualDNAId: base.visualDNAId, sourceAssetIds: base.assets.map(item => item.id), axes: ["composition", "color", "typography", "lighting"], seed: "phase-1-final" });
  const variant = (await database.table<ExplorationVariant, EntityId>("explorationVariants").where("explorationId").equals(explorationResult.explorationId).first()); if (!variant) throw new Error("Exploration variant missing");
  const [project, brief, research, moodboard, visualDNA, direction, exploration, insights] = await Promise.all([required<Project>(database, "projects", base.projectId), required<ProjectBrief>(database, "briefs", base.briefId), required<ResearchSession>(database, "researchSessions", base.researchSessionId), required<Moodboard>(database, "moodboards", base.moodboardId), required<VisualDNA>(database, "visualDna", base.visualDNAId), required<Direction>(database, "directions", lockedDirectionId), required<Exploration>(database, "explorations", explorationResult.explorationId), database.table<ResearchInsight, EntityId>("researchInsights").where("projectId").equals(base.projectId).toArray()]);
  const structuredPrompt = new PromptCompiler().compile({ project, brief, research, insights, moodboard, visualDNA, direction, exploration, variant, constraints: ["保持来源可追溯"] }); const compiled = await new PromptAdapterService(deterministicPromptAdapters, database, { entityIdFactory: base.nextId }).compile(structuredPrompt, "generic");
  const jobs = new GenerationJobService(database, { entityIdFactory: base.nextId }); const queued = await jobs.queue({ projectId: base.projectId, promptVersionId: compiled.promptVersion.id, seed: `final-${String(caseNumber)}` }); const completed = await jobs.run(queued.jobId); if (!completed.result) throw new Error("Generation result missing"); const generated = await new GeneratedAssetService(database, { entityIdFactory: base.nextId }).persist({ projectId: base.projectId, jobId: queued.jobId, result: completed.result }); const reviewed = await new ReviewService(database, { entityIdFactory: base.nextId }).review(base.projectId, generated.id);
  const map = await ensureDecisionMap(base.projectId, database, base.nextId); const adapter = new EntityCanvasAdapter(database, { entityIdFactory: base.nextId }); const insightId = insights[0]?.id; const opportunity = await database.table<{ id: EntityId }, EntityId>("researchOpportunities").where("projectId").equals(base.projectId).first(); const refs = [["brief", base.briefId], ["research", base.researchSessionId], ...(insightId ? [["insight", insightId] as const] : []), ...(opportunity ? [["opportunity", opportunity.id] as const] : []), ["moodboard", base.moodboardId], ["direction", lockedDirectionId], ["exploration", exploration.id], ["prompt", compiled.promptVersion.id], ["generated_asset", generated.id], ["asset", generated.assetId], ["review", reviewed.review.id]] as const; for (const [index, ref] of refs.entries()) await adapter.add(base.projectId, map.canvas.id, ref[0], ref[1], { x: (index % 4) * 260, y: Math.floor(index / 4) * 190 }); const edges = await new LineageEdgeService(database).rebuild(base.projectId, map.canvas.id);
  return { ...base, lockedDirectionId, exploration, variant, variants: await database.table<ExplorationVariant, EntityId>("explorationVariants").where("explorationId").equals(exploration.id).toArray(), structuredPrompt, promptVersion: compiled.promptVersion, generationResult: completed.result, generated, review: reviewed.review, reviewRubric: reviewed.rubric, map, edges, insights, opportunities: await database.table("researchOpportunities").where("projectId").equals(base.projectId).toArray(), moodboard, visualDNA, directions: await database.table<Direction, EntityId>("directions").where("projectId").equals(base.projectId).toArray() };
}
