import { useEffect, useMemo, useState } from "react";
import { liveQuery, type Subscription } from "dexie";
import { EntityCanvasAdapter, getDecisionEntityRoute } from "../../application/canvas/index.js";
import type { CanvasNodeEntityType } from "../../domain/canvas/index.js";
import type { EntityId, ProjectId } from "../../domain/shared/id.js";
import type { MuseDatabase } from "../../db/database.js";

export interface DecisionEntityView { readonly title: string; readonly status: string; readonly sources: readonly string[]; readonly fields: readonly (readonly [string, string])[]; }
export function describeDecisionEntity(entityType: CanvasNodeEntityType, entity: Record<string, unknown>): DecisionEntityView { const titleValue = entity.name ?? entity.title ?? entity.goal ?? entity.summary ?? entity.query ?? entity.statement ?? entity.promptText ?? `${entityType} 节点`; const statusValue = entity.status ?? entity.state ?? (typeof entity.version === "number" ? `V${String(entity.version)}` : "已连接"); const sources = Object.entries(entity).filter(([key]) => key.endsWith("Id") || key.endsWith("Ids")).flatMap(([, value]) => Array.isArray(value) ? value.filter(item => typeof item === "string") : typeof value === "string" ? [value] : []); const fields = Object.entries(entity).filter(([key, value]) => !["id", "projectId", "createdAt", "updatedAt"].includes(key) && (typeof value === "string" || typeof value === "number")).slice(0, 6).map(([key, value]) => [key, String(value)] as const); return { title: String(titleValue), status: String(statusValue), sources, fields }; }
export function subscribeDecisionEntity(adapter: EntityCanvasAdapter, projectId: ProjectId, entityType: CanvasNodeEntityType, entityId: EntityId, next: (value: DecisionEntityView | undefined, error?: unknown) => void): Subscription { return liveQuery(() => adapter.resolve(projectId, entityType, entityId)).subscribe({ next: entity => next(describeDecisionEntity(entityType, entity)), error: reason => next(undefined, reason) }); }
export function DecisionNodeInspector({ database, projectId, selection }: { readonly database: MuseDatabase; readonly projectId: ProjectId; readonly selection?: { readonly entityId: EntityId; readonly entityType: CanvasNodeEntityType } }) { const adapter = useMemo(() => new EntityCanvasAdapter(database), [database]); const [view, setView] = useState<DecisionEntityView>(); const [error, setError] = useState(""); useEffect(() => { setView(undefined); setError(""); if (!selection) return; const subscription = subscribeDecisionEntity(adapter, projectId, selection.entityType, selection.entityId, (value, reason) => { setView(value); setError(reason instanceof Error ? reason.message : reason ? "实体读取失败" : ""); }); return () => subscription.unsubscribe(); }, [adapter, projectId, selection?.entityId, selection?.entityType]); if (!selection) return <section><h2>节点检查器</h2><p>选择节点查看实时实体信息。</p></section>; if (error) return <section><h2>节点检查器</h2><p role="alert">实体已删除、缺失或不属于当前项目。</p></section>; if (!view) return <section><h2>节点检查器</h2><p role="status">正在读取实体…</p></section>; const route = getDecisionEntityRoute(projectId, selection.entityType, selection.entityId); return <section><h2>{view.title}</h2><span>{view.status}</span><dl>{view.fields.map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><h3>来源引用</h3>{view.sources.length ? <ul>{view.sources.map(source => <li key={source}>{source}</li>)}</ul> : <p>无上游引用</p>}{route.ok ? <a href={route.route}>打开对应工作页面</a> : <p role="status">当前节点没有可用目标页面。</p>}</section>; }
